# Generated by Django 4.0.4 on 2022-06-23 20:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registroanimales', '0005_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 17, 3, 19, 485939)),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
