# Generated by Django 4.0.4 on 2022-06-23 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroanimales', '0006_alter_publicacion_fecha_publicacion_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 17, 55, 53, 593242)),
        ),
    ]
