# Generated by Django 4.0.4 on 2022-06-24 16:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registroanimales', '0008_familia_user_alter_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2022, 6, 24, 13, 43, 11, 110068)),
        ),
    ]
